In [5]:
import findspark
findspark.init('/home/ubuntu/spark-2.1.1-bin-hadoop2.7')
import pyspark
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('Construct_the_data_entire_data_check').getOrCreate()
df = spark.read.csv('../Bike-Sharing-Dataset-hour.csv', header=True, inferSchema=True)
    
df.createOrReplaceTempView("dataset")
#query to count the data for the specific year and month
df = spark.sql("SELECT COUNT(dteday) FROM dataset ")
df.show()

+-------------+
|count(dteday)|
+-------------+
|        17544|
+-------------+

In [6]:
#query to retrieve the data for the specific year and month
df = spark.sql("SELECT * FROM dataset ORDER BY instant ")

import pandas as pd
pd.DataFrame(df.take(df.count()), columns=df.columns)

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,0,2011-12-25,4,0,12,4,0,0,0,2,0.4969,0.4757,0.6272,0.1900,35,153,188
1,0,2012-10-29,4,1,10,12,0,1,1,2,0.4969,0.4757,0.6272,0.1900,35,153,188
2,0,2011-01-18,1,0,1,8,0,2,1,2,0.4969,0.4757,0.6272,0.1900,35,153,188
3,0,2012-10-29,4,1,10,13,0,1,1,2,0.4969,0.4757,0.6272,0.1900,35,153,188
4,0,2012-10-29,4,1,10,14,0,1,1,2,0.4969,0.4757,0.6272,0.1900,35,153,188
5,0,2011-02-22,1,0,2,2,0,2,1,2,0.4969,0.4757,0.6272,0.1900,35,153,188
6,0,2011-01-18,1,0,1,9,0,2,1,2,0.4969,0.4757,0.6272,0.1900,35,153,188
7,0,2012-10-29,4,1,10,15,0,1,1,2,0.4969,0.4757,0.6272,0.1900,35,153,188
8,0,2012-10-29,4,1,10,16,0,1,1,2,0.4969,0.4757,0.6272,0.1900,35,153,188
9,0,2011-01-18,1,0,1,10,0,2,1,2,0.4969,0.4757,0.6272,0.1900,35,153,188
10,0,2012-10-29,4,1,10,17,0,1,1,2,0.4969,0.4757,0.6272,0.1900,35,153,188
11,0,2012-10-29,4,1,10,18,0,1,1,2,0.4969,0.4757,0.6272,0.1900,35,153,188
12,0,2011-02-22,1,0,2,3,0,2,1,2,0.4969,0.4757,0.6272,0.1900,35,153,188
13,0,2011-01-18,1,0,1,11,0,2,1,2,0.4969,0.4757,0.6272,0.1900,35,153,188
14,0,2012-10-29,4,1,10,19,0,1,1,2,0.4969,0.4757,0.6272,0.1900,35,153,188
15,0,2011-08-27,3,0,8,23,0,6,0,2,0.4969,0.4757,0.6272,0.1900,35,153,188
16,0,2011-12-26,4,0,12,3,0,1,1,2,0.4969,0.4757,0.6272,0.1900,35,153,188
17,0,2012-10-29,4,1,10,20,0,1,1,2,0.4969,0.4757,0.6272,0.1900,35,153,188
18,0,2011-01-19,1,0,1,3,0,3,1,2,0.4969,0.4757,0.6272,0.1900,35,153,188
19,0,2012-10-29,4,1,10,21,0,1,1,2,0.4969,0.4757,0.6272,0.1900,35,153,188
20,0,2012-10-29,4,1,10,22,0,1,1,2,0.4969,0.4757,0.6272,0.1900,35,153,188
21,0,2011-02-22,1,0,2,4,0,2,1,2,0.4969,0.4757,0.6272,0.1900,35,153,188
22,0,2011-01-22,1,0,1,5,0,6,0,2,0.4969,0.4757,0.6272,0.1900,35,153,188
23,0,2012-10-29,4,1,10,23,0,1,1,2,0.4969,0.4757,0.6272,0.1900,35,153,188
24,0,2012-10-30,4,1,10,0,0,2,1,2,0.4969,0.4757,0.6272,0.1900,35,153,188
25,0,2011-01-23,1,0,1,4,0,0,0,2,0.4969,0.4757,0.6272,0.1900,35,153,188
26,0,2012-10-30,4,1,10,1,0,2,1,2,0.4969,0.4757,0.6272,0.1900,35,153,188
27,0,2012-10-30,4,1,10,2,0,2,1,2,0.4969,0.4757,0.6272,0.1900,35,153,188
28,0,2011-02-22,1,0,2,5,0,2,1,2,0.4969,0.4757,0.6272,0.1900,35,153,188
29,0,2011-01-24,1,0,1,2,0,1,1,2,0.4969,0.4757,0.6272,0.1900,35,153,188
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17514,17350,2012-12-30,1,1,12,18,0,0,0,2,0.2400,0.2121,0.4400,0.2985,12,113,125
17515,17351,2012-12-30,1,1,12,19,0,0,0,1,0.3400,0.3636,0.6100,0.0000,16,86,102
17516,17352,2012-12-30,1,1,12,20,0,0,0,1,0.2200,0.1970,0.4700,0.3284,9,63,72
17517,17353,2012-12-30,1,1,12,21,0,0,0,1,0.2000,0.2121,0.5100,0.1642,5,42,47
17518,17354,2012-12-30,1,1,12,22,0,0,0,1,0.2000,0.1970,0.5500,0.1940,6,30,36
17519,17355,2012-12-30,1,1,12,23,0,0,0,1,0.2000,0.1970,0.5100,0.2239,10,39,49
17520,17356,2012-12-31,1,1,12,0,0,1,1,1,0.1800,0.1818,0.5500,0.1940,4,30,34
17521,17357,2012-12-31,1,1,12,1,0,1,1,1,0.1800,0.1818,0.5500,0.1940,6,13,19
17522,17358,2012-12-31,1,1,12,2,0,1,1,1,0.1600,0.1667,0.5900,0.1642,3,8,11
17523,17359,2012-12-31,1,1,12,3,0,1,1,1,0.1600,0.1818,0.5900,0.1045,0,1,1
17524,17360,2012-12-31,1,1,12,4,0,1,1,1,0.1400,0.1667,0.6900,0.1045,0,3,3
17525,17361,2012-12-31,1,1,12,5,0,1,1,1,0.1600,0.1515,0.6400,0.1940,0,9,9
17526,17362,2012-12-31,1,1,12,6,0,1,1,1,0.1600,0.1667,0.6400,0.1642,0,40,40
17527,17363,2012-12-31,1,1,12,7,0,1,1,1,0.1600,0.1818,0.6400,0.1343,2,83,85
17528,17364,2012-12-31,1,1,12,8,0,1,1,1,0.1400,0.1515,0.6900,0.1343,9,187,196
17529,17365,2012-12-31,1,1,12,9,0,1,1,2,0.1800,0.2121,0.6400,0.1045,13,144,157
17530,17366,2012-12-31,1,1,12,10,0,1,1,2,0.2000,0.2121,0.6900,0.1343,33,87,120
17531,17367,2012-12-31,1,1,12,11,0,1,1,2,0.2200,0.2273,0.6000,0.1940,43,114,157
17532,17368,2012-12-31,1,1,12,12,0,1,1,2,0.2400,0.2273,0.5600,0.1940,52,172,224
17533,17369,2012-12-31,1,1,12,13,0,1,1,2,0.2600,0.2576,0.4400,0.1642,38,165,203
17534,17370,2012-12-31,1,1,12,14,0,1,1,2,0.2800,0.2727,0.4500,0.2239,62,185,247
17535,17371,2012-12-31,1,1,12,15,0,1,1,2,0.2800,0.2879,0.4500,0.1343,69,246,315
17536,17372,2012-12-31,1,1,12,16,0,1,1,2,0.2600,0.2576,0.4800,0.1940,30,184,214
17537,17373,2012-12-31,1,1,12,17,0,1,1,2,0.2600,0.2879,0.4800,0.0896,14,150,164
17538,17374,2012-12-31,1,1,12,18,0,1,1,2,0.2600,0.2727,0.4800,0.1343,10,112,122
17539,17375,2012-12-31,1,1,12,19,0,1,1,2,0.2600,0.2576,0.6000,0.1642,11,108,119
17540,17376,2012-12-31,1,1,12,20,0,1,1,2,0.2600,0.2576,0.6000,0.1642,8,81,89
17541,17377,2012-12-31,1,1,12,21,0,1,1,1,0.2600,0.2576,0.6000,0.1642,7,83,90
17542,17378,2012-12-31,1,1,12,22,0,1,1,1,0.2600,0.2727,0.5600,0.1343,13,48,61
17543,17379,2012-12-31,1,1,12,23,0,1,1,1,0.2600,0.2727,0.6500,0.1343,12,37,49